<?php

return [
    'drinks' => [
        [
            'id'    => 'espresso',
            'label' => 'Espresso',
            'items' => [
                ['name' => 'Fa-me Signature Latte',    'prices' => ['hot' => 120, 'iced16' => 120, 'iced22' => 140], 'badge' => 'Signature'],
                ['name' => 'Spanish Latte',             'prices' => ['hot' => 120, 'iced16' => 120, 'iced22' => 140], 'badge' => 'Bestseller'],
                ['name' => 'Caffè Latte',               'prices' => ['hot' => 120, 'iced16' => 120, 'iced22' => 140]],
                ['name' => 'Hazelnut Latte',            'prices' => ['hot' => 140, 'iced16' => 140, 'iced22' => 160]],
                ['name' => 'Caramel Macchiato',         'prices' => ['hot' => 140, 'iced16' => 140, 'iced22' => 160]],
                ['name' => 'Mocha Latte',               'prices' => ['hot' => 140, 'iced16' => 140, 'iced22' => 160]],
                ['name' => 'Dark Mocha Latte',          'prices' => ['hot' => 140, 'iced16' => 140, 'iced22' => 160]],
                ['name' => 'Biscoff Latte',             'prices' => ['hot' => 160, 'iced16' => 160, 'iced22' => 180]],
                ['name' => 'Oreo Latte',                'prices' => ['iced16' => 160]],
                ['name' => 'Peanut Butter Latte',       'prices' => ['iced16' => 140, 'iced22' => 140]],
                ['name' => 'Americano',                 'prices' => ['hot' => 100, 'iced16' => 100]],
                ['name' => 'Ca Phe Sua Da',             'prices' => ['iced16' => 120]],
                ['name' => 'Chocnut Ca Phe Sua Da',     'prices' => ['iced16' => 150]],
                ['name' => 'Greek Frappé',              'prices' => ['iced16' => 120]],
            ],
        ],
        [
            'id'    => 'non-espresso',
            'label' => 'Non-Espresso',
            'items' => [
                ['name' => 'Choco Latte',       'prices' => ['hot' => 130, 'iced16' => 130, 'iced22' => 150]],
                ['name' => 'Dark Choco Latte',  'prices' => ['hot' => 130, 'iced16' => 130, 'iced22' => 150]],
                ['name' => 'Strawberry Latte',  'prices' => ['iced16' => 130, 'iced22' => 150]],
                ['name' => 'Blueberry Latte',   'prices' => ['iced16' => 130, 'iced22' => 150]],
                ['name' => 'Peach Latte',       'prices' => ['iced16' => 130, 'iced22' => 150]],
            ],
        ],
        [
            'id'    => 'matcha',
            'label' => 'Matcha',
            'items' => [
                ['name' => 'Matcha Tea',               'prices' => ['hot' => 150]],
                ['name' => 'Matcha Latte',             'prices' => ['hot' => 170, 'iced16' => 170]],
                ['name' => 'Peachy Matcha',            'prices' => ['iced16' => 170]],
                ['name' => 'Matcha Yakult',            'prices' => ['iced16' => 190]],
                ['name' => 'Dirty Matcha Latte',       'prices' => ['iced16' => 190]],
                ['name' => 'Caramel Matcha Latte',     'prices' => ['iced16' => 190]],
                ['name' => 'Strawberry Matcha Latte',  'prices' => ['iced16' => 190]],
                ['name' => 'Blueberry Matcha Latte',   'prices' => ['iced16' => 190]],
                ['name' => 'Peachy Matcha Latte',      'prices' => ['iced16' => 190]],
                ['name' => 'Matcha Biscoff Latte',     'prices' => ['iced16' => 220]],
            ],
        ],
        [
            'id'    => 'frappuccinos',
            'label' => 'Frappuccinos',
            'items' => [
                ['name' => 'Mocha',              'prices' => ['iced16' => 160, 'iced22' => 180]],
                ['name' => 'Dark Mocha',         'prices' => ['iced16' => 160, 'iced22' => 180]],
                ['name' => 'Espresso Caramel',   'prices' => ['iced16' => 160, 'iced22' => 180]],
                ['name' => 'Coffee Jelly',       'prices' => ['iced16' => 160, 'iced22' => 180]],
                ['name' => 'Peanut Butter',      'prices' => ['iced16' => 150], 'badge' => 'Coffee'],
                ['name' => 'Biscoff',            'prices' => ['iced16' => 180, 'iced22' => 200], 'badge' => 'Coffee'],
                ['name' => 'Choco',              'prices' => ['iced16' => 150, 'iced22' => 170]],
                ['name' => 'Dark Choco',         'prices' => ['iced16' => 150, 'iced22' => 170]],
                ['name' => 'Strawberry',         'prices' => ['iced16' => 150, 'iced22' => 170]],
                ['name' => 'Blueberry',          'prices' => ['iced16' => 150, 'iced22' => 170]],
                ['name' => 'Caramel',            'prices' => ['iced16' => 150, 'iced22' => 170]],
                ['name' => 'Oreo',               'prices' => ['iced16' => 150, 'iced22' => 170]],
                ['name' => 'Peach',              'prices' => ['iced16' => 150, 'iced22' => 170]],
                ['name' => 'Strawberry Oreo',    'prices' => ['iced16' => 170, 'iced22' => 190]],
                ['name' => 'Biscoff (Non-Coffee)','prices' => ['iced16' => 170, 'iced22' => 190]],
                ['name' => 'Matcha',             'prices' => ['iced16' => 190]],
            ],
        ],
        [
            'id'    => 'soda',
            'label' => 'Soda & More',
            'items' => [
                ['name' => 'Strawberry Lemonade',       'prices' => ['iced16' => 100, 'iced22' => 120]],
                ['name' => 'Blueberry Lemonade',        'prices' => ['iced16' => 100, 'iced22' => 120]],
                ['name' => 'Green Apple Lemonade',      'prices' => ['iced16' => 100, 'iced22' => 120]],
                ['name' => 'Tropical Horizon Mocktail', 'prices' => ['iced22' => 150]],
                ['name' => 'Sunset Squeeze Mocktail',   'prices' => ['iced22' => 150]],
                ['name' => 'Espresso Romano',           'prices' => ['iced16' => 150]],
                ['name' => 'Double Berry Smoothie',     'prices' => ['iced16' => 220, 'iced22' => 240]],
                ['name' => 'Triple Berry Smoothie',     'prices' => ['iced16' => 220, 'iced22' => 240]],
            ],
        ],
    ],
    'food' => [
        [
            'id'    => 'indonesian',
            'label' => 'Indonesian Specials',
            'items' => [
                ['name' => 'Nasi Goreng',    'price' => 230, 'desc' => 'Indonesian-style fried rice with aromatics and savory house seasoning.'],
                ['name' => 'Kwetiau',        'price' => 250, 'desc' => 'Stir-fried flat rice noodles with vegetables and a light soy blend.'],
                ['name' => 'Pork Rendang',   'price' => 300, 'desc' => 'Slow-braised pork in rich rendang sauce.', 'note' => 'Available Fri, Sat & Sun only', 'badge' => 'Weekend Special'],
                [
                    'name'     => 'Martabak Manis',
                    'price'    => '190–230',
                    'desc'     => 'Traditional Indonesian sweet stuffed pancake with your choice of filling.',
                    'variants' => [
                        ['label' => 'Cheese',        'price' => 190],
                        ['label' => 'Chocolate',     'price' => 210],
                        ['label' => 'Choco Cheese',  'price' => 230],
                    ],
                ],
            ],
        ],
        [
            'id'    => 'snacks',
            'label' => 'Pasta & Snacks',
            'items' => [
                ['name' => 'Carbonara',          'price' => 220, 'desc' => 'Creamy pasta tossed in rich carbonara sauce.'],
                ['name' => 'Nachos',             'price' => 240, 'desc' => 'Loaded nachos topped with Mexican beef, fresh veggies, and cheese dip. Perfect for groups.'],
                ['name' => 'Fries and Poppers',  'price' => 170, 'desc' => 'Crispy fries and chicken poppers — available in Barbecue, Sour Cream, Cheese, or Sweet Corn.', 'note' => 'Choose: BBQ · Sour Cream · Cheese · Sweet Corn'],
                ['name' => 'Buchi (4 pcs)',      'price' => 80,  'desc' => 'Sweet sesame rice balls with red bean paste filling.'],
            ],
        ],
    ],
];
